apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-01-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-01
    spec:
      containers:
      - image: appsoa/docker-centos-webapp-wordpress:latest
        name:  wordpress-01
        ports:
        - containerPort: 80
        volumeMounts:
      #   - mountPath: /www
      #     name: persistent-volume
      # volumes:
      # - name: persistent-volume
      #   # This GCE PD must already exist.
      #   gcePersistentDisk:
      #     pdName: vpc-01-persistent-disk-outphiit-01
      #     fsType: ext4